config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update', as: :update_password

  # destroy
  delete 'logout', to: 'sessions#destroy'
  # index
  root to: 'main#index'
  # reigistration
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  # login in
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'about', to: 'about#index'
  # paswords reset
  get 'password/reset', to: 'password_reset#new'
  post 'password/reset', to: 'password_reset#create'
  # paswords reset edit
  get 'password/reset/edit', to: 'password_reset#edit'
  post 'password/reset/edit', to: 'password_reset#update'
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# get '/about-us', to: 'about#index', as: :about

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

   attribute :user

end

app/models/user.rb
# frozen_string_literal: true

# email: string
# password_digest: string
#
# password:string
# password_confirmation: string
class User < ApplicationRecord
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i, message: 'must be a valid email address' }
  validates :password, presence: true
  validates :password_confirmation, presence: true

  validate :password_match

  has_secure_password

  private

  def password_match
    errors.add(:password, 'does not match password confirmation') unless password == password_confirmation
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true



class ApplicationController < ActionController::Base

  before_action :set_current_user

  def set_current_user

    return unless session[:user_id]
    Current.user = User.find_by(id: session[:user_id])
  end


 def require_user_logged_in!
    redirect_to sign_in_path, alert: 'You must be logged in' if Current.user.nil?
  end

end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!
  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end


end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user.presence?
      # sent email
      # PasswordMailer.with(user: @user).deliver_later
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: 'we have sent a link to your email to reset your password'
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

#  registration parameters stored if available
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User was successfully created'
    else
      # redirect_to sign_up_path
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# delete user id form model

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])

      session[:user_id] = user.id

      redirect_to root_path, notice: 'Login successful'

    else

      flash[:alert] = 'Invalid email or password'

      render :new, status: :unprocessable_entity

    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: 'Logout successful'
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link >

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body class='container'>
    <% # nav bar %>
    <%= render partial: "shared/navbar" %>
    <% # main content %>
    <div class='container'>
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/main/index.html.erb
<div class='d-flex flex-column align-item-center justify-content-center'>
  <h1>Welcome to ruby on rails</h1>
  
</div>

app/views/password/edit.html.erb
<p>Find me in app/views/password/edit.html.erb</p>
<h1>edit password</h1>
<%= form_with model: Current.user, url: edit_password_path, method: :patch, class: "row g-3" do |form| %>
  <% if form.object.errors.any? %>
    <div class='alert alert-danger'>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class='col-12 col-md-6'>
    <%= form.label :password %><br>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>
  <div class='col-12 col-md-6'>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>
  <div class='col-12 col-md-6'>
    <%= form.submit "Update Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_reset/new.html.erb
<h1>forget your password</h1>
<p>Find me in app/views/password_reset/new.html.erb</p>
<% # login form %>
<%= form_with url: password_reset_path, method: :post, class: "row g-3" do |form| %>
  <div class='col-12 col-md-6'>
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control", placeholder: "sdfs@gmail.com" %>
  </div>
  <div class='col-12 col-md-6'>
    <%= form.submit "Reset", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>


<% if flash[:alert]  %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<h1>New user</h1>

<%= form_with model: @user, url: sign_up_path, method: :post, class: "row g-3" do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <p>Please try again later</p>
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>


  <div class='col-12'>
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control", placeholder: "sdfs@gmail.com" %>
  </div>

  <div class='col-12 col-md-6'>
    <%= form.label :password %><br>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>
  <div class='col-12 col-md-6'>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>

  <div class='col-12 col-md-6'>
    <%= form.submit "sign up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", 'aria-current': "page" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <%# right nav %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item mt-md-2 mx-md-2 ">
            <%= link_to Current.user.email, edit_password_path, class:'nav-link' %>
          </li>
          <li>
            <%= button_to "logout", logout_path, class: "btn btn-info mt-2", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>